# Generated by Django 5.2 on 2025-04-22 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="people_available",
            new_name="capacity",
        ),
    ]
