# Generated by Django 5.2 on 2025-07-29 09:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="center",
            old_name="name",
            new_name="user_name",
        ),
        migrations.AddField(
            model_name="center",
            name="center_building_address",
            field=models.CharField(default="N/A", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="center",
            name="center_full_name",
            field=models.CharField(default="N/A", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="center",
            name="center_short_name",
            field=models.CharField(default="N/A", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="center",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="center",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="center",
            name="user_password",
            field=models.CharField(default="N/A", max_length=128),
            preserve_default=False,
        ),
    ]
