# Generated by Django 5.2 on 2025-07-29 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_name_center_user_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="center",
            name="user_name",
        ),
        migrations.RemoveField(
            model_name="center",
            name="user_password",
        ),
    ]
