# Generated by Django 5.2 on 2025-08-04 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_center_user_name_remove_center_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='id',
        ),
        migrations.AddField(
            model_name='center',
            name='center_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
