# Generated by Django 5.2 on 2025-04-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Math Club', max_length=100)),
                ('day', models.CharField(default='Wednesday', max_length=50)),
                ('time', models.CharField(default='1:00 PM - 2:00 PM', max_length=50)),
                ('location', models.CharField(default='Bldg 18 at 307', max_length=100)),
            ],
        ),
    ]
