# Generated by Django 5.2 on 2025-04-25 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubinfo',
            name='day',
        ),
        migrations.RemoveField(
            model_name='clubinfo',
            name='time',
        ),
        migrations.AddField(
            model_name='clubinfo',
            name='advisors',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='clubinfo',
            name='advisors_email',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='clubinfo',
            name='meetings',
            field=models.CharField(default='Wednesday at 1:00 PM - 2:00 PM', max_length=200),
        ),
    ]
