# Generated by Django 5.2 on 2025-04-25 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_remove_clubinfo_day_remove_clubinfo_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubinfo',
            name='meetings',
            field=models.CharField(default='Wednesday at 1:00 PM - 2:00 PM', max_length=100),
        ),
    ]
