# Generated by Django 5.2 on 2025-04-25 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_alter_clubinfo_meetings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubinfo',
            old_name='advisors',
            new_name='advisor_email',
        ),
        migrations.RemoveField(
            model_name='clubinfo',
            name='advisors_email',
        ),
        migrations.RemoveField(
            model_name='clubinfo',
            name='meetings',
        ),
        migrations.AddField(
            model_name='clubinfo',
            name='advisor',
            field=models.CharField(default='Mr Potato', max_length=50),
        ),
        migrations.AddField(
            model_name='clubinfo',
            name='day',
            field=models.CharField(default='Wednesday', max_length=50),
        ),
        migrations.AddField(
            model_name='clubinfo',
            name='time',
            field=models.CharField(default='1:00 PM - 2:00 PM', max_length=50),
        ),
    ]
