# Generated by Django 5.2 on 2025-04-25 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_rename_advisor_clubinfo_advisors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubinfo',
            name='advisors',
            field=models.JSONField(default=list, max_length=50),
        ),
    ]
