# Generated by Django 5.2 on 2025-04-25 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_alter_clubinfo_advisors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubinfo',
            name='advisors',
            field=models.JSONField(default=list, max_length=100),
        ),
    ]
