# Generated by Django 5.2 on 2025-04-19 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TutoringDailySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=70)),
                ('time', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
