# Generated by Django 5.2 on 2025-04-20 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutoringdailyschedule',
            old_name='class_name',
            new_name='courses',
        ),
        migrations.AddField(
            model_name='tutoringdailyschedule',
            name='weekday',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], default='Monday', max_length=9),
        ),
        migrations.AlterField(
            model_name='tutoringdailyschedule',
            name='location',
            field=models.CharField(default='MRC', max_length=50),
        ),
        migrations.AlterField(
            model_name='tutoringdailyschedule',
            name='subject',
            field=models.CharField(default='Math', max_length=100),
        ),
    ]
