# Generated by Django 5.2 on 2025-04-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0002_rename_class_name_tutoringdailyschedule_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoringdailyschedule',
            name='courses',
            field=models.JSONField(default=list),
        ),
    ]
