# Generated by Django 5.2 on 2025-07-29 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_name_center_user_name_and_more"),
        ("tutoring", "0003_alter_tutoringdailyschedule_courses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutoringdailyschedule",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.center"
            ),
        ),
    ]
