# Generated by Django 5.2 on 2025-07-30 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutoring", "0004_alter_tutoringdailyschedule_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutoringdailyschedule",
            name="location",
            field=models.CharField(default="MRC", max_length=50),
        ),
    ]
