# Generated by Django 5.2 on 2025-07-31 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0005_alter_tutoringdailyschedule_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoringdailyschedule',
            name='tutors',
            field=models.CharField(default='None', max_length=40),
        ),
        migrations.AlterField(
            model_name='tutoringdailyschedule',
            name='location',
            field=models.CharField(default='CSM', max_length=50),
        ),
        migrations.AlterField(
            model_name='tutoringdailyschedule',
            name='time',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
