# Generated by Django 5.2 on 2025-08-04 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_center_id_center_center_id'),
        ('tutoring', '0006_tutoringdailyschedule_tutors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoringdailyschedule',
            name='courses',
            field=models.CharField(default='Empty', max_length=100),
        ),
        migrations.AlterField(
            model_name='tutoringdailyschedule',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.center'),
        ),
    ]
