# Generated by Django 5.2 on 2025-08-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_center_id_center_center_id'),
        ('tutoring', '0007_alter_tutoringdailyschedule_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoringdailyschedule',
            name='subject',
            field=models.CharField(db_index=True, default='Math', max_length=100),
        ),
        migrations.AlterField(
            model_name='tutoringdailyschedule',
            name='weekday',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], db_index=True, default='Monday', max_length=9),
        ),
        migrations.AddIndex(
            model_name='tutoringdailyschedule',
            index=models.Index(fields=['weekday', 'subject'], name='tutoring_tu_weekday_68fea3_idx'),
        ),
    ]
