# Generated by Django 5.2 on 2025-04-19 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.center"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Still available"),
                    ("unavailable", "Not available"),
                ],
                default="available",
                max_length=20,
            ),
        ),
    ]
