# Generated by Django 5.2 on 2025-07-30 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_center_user_name_remove_center_user_password"),
        ("resources", "0002_alter_item_location_alter_item_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.center",
            ),
        ),
    ]
